# https://github.com/air-verse/air?tab=readme-ov-file#installation-and-usage-for-docker-users-who-dont-want-to-use-air-image

# defines a multi container service that could contain multiple services
services:
  # service-1: named service app
  app:
    # container name
    container_name: app
    # name for the image
    image: application-app-dev
    # section defines how to build the image used for the application
    build:
      # defines the build context - just take the current location where the file is within
      context: ./app
      # defines the Dockerfile to use. It is located relative to the given context path "."
      dockerfile: Dockerfile-app
      # target of the build as defined in the dockerfile
      target: dev
      # section defines port mapping
    ports:
      # site access from browser - container port 3000 (left side) can be accessed by the host on port 3000 (right side)
      - 3000:3000
      # section defines volume mappings
    volumes:
      # mount the current directory "." (left side) : to the location "app" within the container (right side)
      - type: bind
        source: ./app
        target: /app
  # service 2: Database ProstgreSQL
  db:
    # container name
    container_name: postgres
    # name for the image
    image: application-db-dev
    # section defines how to build the image used for the database
    build:
      # defines the build context - just take the current location where the file is within
      context: ./db
      # defines the Dockerfile to use. It is located relative to the given context path "."
      dockerfile: Dockerfile-db
      # target of the build as defined in the dockerfile
      target: dev
    # container port 5001 (left side) can be accessed by the host on port 5432 (right side)
    ports:
      - 5001:5432
    # mount the current directory "./db" (left side) : to the location "db" within the container (right side)
    volumes:
    - type: bind
      source: ./db
      target: /db
    # set environment variables
    environment:
      # 1. username: postgres
      - POSTGRES_USER=postgres
      # 2. password: postgres
      - POSTGRES_PASSWORD=postgres
      # 3. databasename: db
      # POSTGRES_DB: This variable specifies the name of the database that will be created 
      # as part of the PostgreSQL server startup. In this case, it is set to db.
      - POSTGRES_DB=db
      # 4. location for data
      - PGDATA=./db/data
      # 5. username: client user
      - DB_CLIENT_USER=pg
      # 6. password: client user
      - DB_CLIENT_PASSWORD=pgpw