# https://github.com/air-verse/air?tab=readme-ov-file#installation-and-usage-for-docker-users-who-dont-want-to-use-air-image

# defines a multi container service that could contain multiple services
services:
  # service-1: named service app
  app:
    # container name
    container_name: app
    # section defines how to build the image used for the application
    build:
      # defines the build context - just take the current location where the file is within
      context: ./app
      # defines the Dockerfile to use. It is located relative to the given context path "."
      dockerfile: Dockerfile-app
      # section defines port mapping
    ports:
      # container port 3000 (left side) can be accessed by the host on port 3000 (right side)
      - 3000:3000
      # section defines volume mappings
    volumes:
      # mount the current directory "." (left side) : to the location "app" within the container (right side)
      - type: bind
        source: ./app
        target: /app
  # service 2: Database ProstgreSQL
  db:
    # container name
    container_name: postgres
    # section defines how to build the image used for the database
    build:
      # defines the build context - just take the current location where the file is within
      context: ./database
      # defines the Dockerfile to use. It is located relative to the given context path "."
      dockerfile: Dockerfile-db  
    # container port 5001 (left side) can be accessed by the host on port 5432 (right side)
    ports:
      - 5001:5432
    # mount the current directory "./database" (left side) : to the location "database" within the container (right side)
    volumes:
    - type: bind
      source: ./database
      target: /database
    # set environment variables
    environment:
      # 1. username: postgres
      - POSTGRES_USER=postgres
      # 2. password: postgres
      - POSTGRES_PASSWORD=postgres
      # 3. databasename: db
      - POSTGRES_DB=db
      # 4. location for data
      - PGDATA=./database/data