# https://github.com/air-verse/air?tab=readme-ov-file#installation-and-usage-for-docker-users-who-dont-want-to-use-air-image

# defines a multi container service that could contain multiple services
services:
  # service-1: named service app
  app:
    # defines the name of the image to use to run the app
    image: docker_dev-container-app
    # defines the name of the container built based on the previous named image
    container_name: docker_dev-container
    # section defines port mapping
    ports:
      # container port 8080 (left side) can be accessed by the host on port 8080 (right side)
      - 8080:8080
      # section defines volume mappings
    volumes:
      # mount the current directory "." (left side) : to the location "app" within the container (right side)
      - ./:/app