########## DEV IMAGE ##########

# use the alpine postgres image as base
# https://hub.docker.com/_/postgres
FROM postgres:15 AS dev


########## PRD IMAGE ##########

# use the alpine postgres image as base
# https://hub.docker.com/_/postgres
FROM postgres:15 AS prd
